//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTwo
    {
        public string namee { get; set; }
        public string College { get; set; }
        public int ID { get; set; }
    
        public virtual tbOne tbOne { get; set; }
    }
}
